excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://amandeep-singh-in.github.io
title: Awesome
email: 
author: Amandeep Singh
description: My awesome new site
paginate: 3
google_analytics: UA-78755060-1
